- ansible.builtin.debug:
    msg:
      - 'aide-install.yml'

- ansible.builtin.package:
    name: 'aide'
    state: 'present'

- ansible.builtin.template:
    src: 'etc/aide.conf.j2'
    dest: '/etc/aide.conf'
    owner: 'root'
    group: 'root'
    mode: 0o644

- ansible.builtin.command: '/usr/sbin/aide --init --before "database_out=file:/var/lib/aide/aide.db.gz"'
  args:
    creates: '/var/lib/aide/aide.db.gz'
  changed_when: false
  failed_when: false
  async: 45
  poll: 0
