- ansible.builtin.debug:
    msg:
      - 'aide-timer.yml'

- ansible.builtin.template:
    src: 'etc/systemd/system/aide-check.service.j2'
    dest: '/etc/systemd/system/aide-check.service'
    owner: 'root'
    group: 'root'
    mode: 0o644
  notify: 'stig: systemctl daemon-reload'

- ansible.builtin.template:
    src: 'etc/systemd/system/aide-check.timer.j2'
    dest: '/etc/systemd/system/aide-check.timer'
    owner: 'root'
    group: 'root'
    mode: 0o644
  notify: 'stig: systemctl daemon-reload'

- ansible.builtin.systemd:
    name: 'aide-check.timer'
    state: 'started'
    enabled: true
    masked: false
    daemon_reload: true
