- ansible.builtin.debug:
    msg:
      - 'aslr-on.yml'

- ansible.posix.sysctl:
    name: 'kernel.randomize_va_space'
    value: '2'
    sysctl_set: true
    state: 'present'
    reload: true
    ignoreerrors: true
