- ansible.builtin.debug:
    msg:
      - 'auditd-rules-finalize-configure.yml'

# Make the configuration immutable, a reboot is required to change the configuration settings or rulesets.
# The audit.rules file should end with the immutability settings, so this has to be the last (!) rule:

- ansible.builtin.template:
    src: 'etc/audit/rules.d/zz-finalize.rules.j2'
    dest: '/etc/audit/rules.d/zz-finalize.rules'
    owner: 'root'
    group: 'root'
    mode: 0o600
