- ansible.builtin.debug:
    msg:
      - 'auditd-rules-sudolog-configure.yml'

- ansible.builtin.template:
    src: 'etc/audit/rules.d/sudolog.rules.j2'
    dest: '/etc/audit/rules.d/sudolog.rules'
    owner: 'root'
    group: 'root'
    mode: 0o600
