- ansible.builtin.debug:
    msg:
      - 'auditd-max_log_file-configure.yml'

- ansible.builtin.lineinfile:
    path: '/etc/audit/auditd.conf'
    create: true
    regexp: '^max_log_file\s*=.*'
    line: 'max_log_file = {{ stig__auditd_max_log_file }}'
    state: 'present'
