- ansible.builtin.debug:
    msg:
      - 'auditd-rules-scope-configure.yml'

- ansible.builtin.template:
    src: 'etc/audit/rules.d/scope.rules.j2'
    dest: '/etc/audit/rules.d/scope.rules'
    owner: 'root'
    group: 'root'
    mode: 0o600
