- ansible.builtin.debug:
    msg:
      - 'chrony-install.yml'

- block:
  - ansible.builtin.package:
      name: 'chrony'
      state: 'present'
  when:
    - "'systemd-timesyncd.service' not in ansible_facts['services']"
