- ansible.builtin.debug:
    msg:
      - 'core-dump-off.yml'

- ansible.builtin.lineinfile:
    path: '/etc/security/limits.conf'
    regexp: '^[^#].*core'
    line: '*     hard   core    0'
    create: true
    insertbefore: '^# End of file'

- ansible.posix.sysctl:
    name: 'fs.suid_dumpable'
    value: '0'
    state: 'present'
    reload: true
    sysctl_set: true
    ignoreerrors: true
# https://www.freedesktop.org/software/systemd/man/systemd-coredump.html

- ansible.builtin.lineinfile:
    path: '/etc/systemd/coredump.conf'
    create: false
    regexp: '^\s*Storage\s*=\s*'
    state: 'absent'

- ansible.builtin.lineinfile:
    path: '/etc/systemd/coredump.conf'
    create: false
    line: 'Storage=none'
    state: 'present'

- ansible.builtin.lineinfile:
    path: '/etc/systemd/coredump.conf'
    create: false
    regexp: '^\s*ProcessSizeMax\s*=\s*'
    state: 'absent'

- ansible.builtin.lineinfile:
    path: '/etc/systemd/coredump.conf'
    create: false
    line: 'ProcessSizeMax=0'
    state: 'present'
