- ansible.builtin.debug:
    msg:
      - 'cron-restrictions-configure.yml'

- ansible.builtin.file:
    path: '/etc/cron.deny'
    state: 'absent'

- ansible.builtin.stat:
    path: '/etc/cron.allow'
  register: 'p'

- ansible.builtin.file:
    path: '/etc/cron.allow'
    state: '{{ "file" if p.stat.exists else "touch" }}'
    owner: 'root'
    group: 'root'
    mode: 0o600
