- ansible.builtin.debug:
    msg:
      - 'directories-sticky_bit-chmod.yml'

- ansible.builtin.shell: "df --local --portability | awk '{if (NR!=1) print $6}' | xargs -I '{}' find '{}' -xdev -type d \\( -perm -0002 -a ! -perm -1000 \\) 2>/dev/null"
  register: 'shell_output'
  changed_when: false

- ansible.builtin.file:
    path: '{{ item }}'
    mode: 'a+t'
  loop: '{{ shell_output.stdout_lines }}'
  failed_when: 'shell_output.stderr is not defined'
