- ansible.builtin.debug:
    msg:
      - 'dnf-gpgcheck-on.yml'

- ansible.builtin.find:
    paths: '/etc/yum.repos.d'
    patterns: '*.repo'
  register: 'files_matched'

- ansible.builtin.replace:
    # "ini_file" does not work here because the section names all vary
    # "with_fileglob" is against local system files on the Ansible controller
    path: '{{ item }}'
    regexp: 'gpgcheck\s*=\s*0'
    replace: 'gpgcheck=1'
  loop: '{{ files_matched.files | map(attribute="path") | list }}'

- ini_file:
    path: '/etc/dnf/dnf.conf'
    section: 'main'
    option: 'gpgcheck'
    value: '1'
    create: true

- ini_file:
    path: '/etc/dnf/dnf.conf'
    section: 'main'
    option: 'localpkg_gpgcheck'
    value: '1'
    create: true
