- ansible.builtin.debug:
    msg:
      - 'grub-password-configure.yml'

- ansible.builtin.shell: "echo -e '{{ stig__grub2_password }}\n{{ stig__grub2_password }}' | LC_ALL=C /usr/bin/grub2-mkpasswd-pbkdf2 | awk '/hash of / {print $NF}'"
  register: 'stig__grub2_password_hashed'

- ansible.builtin.copy:
    dest: '/boot/efi/EFI/{{ ansible_facts["distribution"] | lower }}/user.cfg'
    content: 'GRUB2_PASSWORD={{ stig__grub2_password_hashed.stdout }}'
  notify:
    - 'stig: grub2-mkconfig EFI'
  when:
    - 'booted_in_efi_mode | bool'

- ansible.builtin.copy:
    dest: '/boot/grub2/user.cfg'
    content: 'GRUB2_PASSWORD={{ stig__grub2_password_hashed.stdout }}'
  notify:
    - 'stig: grub2-mkconfig BIOS'
  when:
    - 'booted_in_bios_mode | bool'
