- ansible.builtin.debug:
    msg:
      - 'grub-chmod.yml'

- block:

  - name: 'Update the Ansible facts to get latest information'
    ansible.builtin.setup: # yamllint disable-line rule:empty-values

  - ansible.posix.mount:
      path: '{{ item.mount }}'
      state: 'present'
      fstype: '{{ item.fstype }}'
      dump: 0
      passno: 2
      src: 'UUID={{ item.uuid }}'
      opts: '{{ item.options | regex_replace("fmask=\\d{3,},?", "") | split(",") | union(["fmask=0077"]) | join(",") }}'
    when: 'item.mount == "/boot/efi"'
    loop: '{{ ansible_facts["mounts"] }}'

  - ansible.builtin.file:
      path: '/boot/efi/EFI/{{ ansible_facts["distribution"] | lower }}/grub.cfg'
      owner: 'root'
      group: 'root'
      mode: 'og-rwx'

  - ansible.builtin.file:
      path: '/boot/efi/EFI/{{ ansible_facts["distribution"] | lower }}/grub.cfg'
      owner: 'root'
      group: 'root'
      mode: 'og-rwx'
    ignore_errors: true # this file could be absent

  when:
    - 'booted_in_efi_mode | bool'


- block:

  - ansible.builtin.file:
      path: '/boot/grub2/grub.cfg'
      owner: 'root'
      ansible.builtin.group: 'root'
      mode: 'og-rwx'

  - ansible.builtin.file:
      path: '/boot/grub2/user.cfg'
      owner: 'root'
      group: 'root'
      mode: 'og-rwx'
    ignore_errors: true

  when:
    - 'booted_in_bios_mode | bool'
