- ansible.builtin.debug:
    msg:
      - 'httpd-login_shell-off.yml'

- ansible.builtin.user:
    name: 'httpd'
    shell: '/sbin/nologin'
  when: 'ansible_facts["os_family"] in ["RedHat"]'

- ansible.builtin.user:
    name: 'apache2'
    shell: '/sbin/nologin'
  when: 'ansible_facts["os_family"] not in ["RedHat"]'
