- ansible.builtin.debug:
    msg:
      - 'httpd-install.yml'

- ansible.builtin.package:
    name: 'httpd'
    state: 'present'

- ansible.builtin.systemd:
    name: 'httpd.service'
    enabled: true

- ansible.builtin.systemd:
    name: 'httpd.service'
    state: 'started'
