- ansible.builtin.debug:
    msg:
      - 'httpd-user_locked-on.yml'

- ansible.builtin.user:
    name: 'httpd'
    password_lock: true
  when: 'ansible_facts["os_family"] in ["RedHat"]'

- ansible.builtin.user:
    name: 'apache2'
    password_lock: true
  when: 'not ansible_facts["os_family"] in ["RedHat"]'
