- ansible.builtin.debug:
    msg:
      - 'issue_net-configure.yml'

- ansible.builtin.template:
    src: 'etc/issue.net.j2'
    dest: '/etc/issue.net'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    regexp: '^#?Banner'
    line: 'Banner /etc/issue.net'
    state: 'present'
    create: true
