- ansible.builtin.debug:
    msg:
      - 'logrotate-daily-configure.yml'

- ansible.builtin.find:
    paths: '/etc/logrotate.d/'
  register: 'files_matched'

- ansible.builtin.replace:
    path: '{{ item }}'
    regexp: '^(\s*)(daily|weekly|monthly|yearly)$'
    replace: '\1daily'
  loop: '{{ files_matched.files | map(attribute="path") | list }}'

- ansible.builtin.replace:
    path: '/etc/logrotate.conf'
    regexp: '^(\s*)(daily|weekly|monthly|yearly)$'
    replace: '\1daily'

- ansible.builtin.lineinfile:
    path: '/etc/cron.daily/logrotate'
    line: '#!/bin/sh'
    insertbefore: 'BOF'
    create: true

- ansible.builtin.lineinfile:
    path: '/etc/cron.daily/logrotate'
    line: '/usr/sbin/logrotate /etc/logrotate.conf'
    regexp: '^[\s]*/usr/sbin/logrotate[\s\S]*/etc/logrotate.conf$'
