- ansible.builtin.debug:
    msg:
      - 'lynis-install.yml'

- ansible.builtin.package:
    name: 'epel-release'
    state: 'present'

- ansible.builtin.package:
    name: 'lynis'
    state: 'present'

- ansible.builtin.command: '/usr/bin/lynis update info'
  changed_when: false
  failed_when: false

- ansible.builtin.command: '/usr/bin/lynis audit system'
  changed_when: false
  failed_when: false
