- ansible.builtin.debug:
    msg:
      - 'motd-chmod.yml'

- ansible.builtin.file:
    path: '/etc/motd'
    state: 'file'
    owner: 'root'
    group: 'root'
    mode: 0o644
  # ignore non-existing file
  ignore_errors: true
