- ansible.builtin.debug:
    msg:
      - 'ntp-install.yml'

- ansible.builtin.package:
    name: 'ntp'
    state: 'present'

- ansible.builtin.lineinfile:
    path: '/etc/sysconfig/ntpd'
    regexp: '^(#)?OPTIONS'
    line: 'OPTIONS="-u ntp:ntp"'
    state: 'present'
    create: true

- ansible.builtin.template:
    src: 'etc/ntp.conf.j2'
    dest: '/etc/ntp.conf'
    mode: 0o644
  notify: 'stig: systemctl restart ntpd'

- name: 'systemctl {{ stig__ntp_service_enabled | bool | ternary("enable", "disable") }} --now ntpd.service'
  ansible.builtin.systemd:
    name: 'ntpd.service'
    enabled: '{{ stig__ntp_service_enabled }}'
    state: '{{ stig__ntp_service_enabled | bool | ternary("started", "stopped") }}'
