- ansible.builtin.debug:
    msg:
      - 'paths-owned_by_root-configure.yml'

- ansible.builtin.shell: "/bin/bash --login -c 'env | grep ^PATH=' | sed -e 's/PATH=//' -e 's/::/:/' -e 's/:$//' -e 's/:/\\n/g'"
  register: 'shell_output'
  changed_when: false
  failed_when: '"." in shell_output.stdout_lines'

- ansible.builtin.file:
    path: '{{ item }}'
    follow: true
    state: 'directory'
    owner: 'root'
    mode: 'o-w,g-w'
  loop: '{{ shell_output.stdout_lines }}'
