- ansible.builtin.debug:
    msg:
      - 'postfix-loopback-only-on.yml'

- ansible.builtin.lineinfile:
    path: '/etc/postfix/main.cf'
    create: false
    regexp: '^inet_interfaces\s*=.*'
    line: 'inet_interfaces = loopback-only'
    state: 'present'
    insertafter: '^inet_interfaces\s*=\s.*'
  notify: 'stig: systemctl restart postfix'
  when:
    - "'postfix.service' in ansible_facts['services']"
