- ansible.builtin.debug:
    msg:
      - 'rsyslog-logging-configure.yml'

- ansible.builtin.lineinfile:
    path: '/etc/rsyslog.conf'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: 'present'
    create: true
  loop:
    - {regexp: '^\*\.emerg',                    line: '*.emerg                  :omusrmsg:*'}               # yamllint disable-line rule:commas
    - {regexp: '^auth,authpriv\.\*',            line: 'auth,authpriv.*          /var/log/secure'}           # yamllint disable-line rule:commas
    - {regexp: '^mail\.\*',                     line: 'mail.*                  -/var/log/mail'}             # yamllint disable-line rule:commas
    - {regexp: '^mail\.info',                   line: 'mail.info               -/var/log/mail.info'}        # yamllint disable-line rule:commas
    - {regexp: '^mail\.warning',                line: 'mail.warning            -/var/log/mail.warn'}        # yamllint disable-line rule:commas
    - {regexp: '^mail\.err',                    line: 'mail.err                 /var/log/mail.err'}         # yamllint disable-line rule:commas
    - {regexp: '^news\.crit',                   line: 'news.crit               -/var/log/news/news.crit'}   # yamllint disable-line rule:commas
    - {regexp: '^news\.err',                    line: 'news.err                -/var/log/news/news.err'}    # yamllint disable-line rule:commas
    - {regexp: '^news\.notice',                 line: 'news.notice             -/var/log/news/news.notice'} # yamllint disable-line rule:commas
    - {regexp: '^\*\.=warning;\*\.=err',        line: '*.=warning;*.=err       -/var/log/warn'}             # yamllint disable-line rule:commas
    - {regexp: '^\*\.crit',                     line: '*.crit                   /var/log/warn'}             # yamllint disable-line rule:commas
    - {regexp: '^\*\.\*;mail\.none;news\.none', line: '*.*;mail.none;news.none -/var/log/messages'}         # yamllint disable-line rule:commas
    - {regexp: '^local0,local1\.\*',            line: 'local0,local1.*         -/var/log/localmessages'}    # yamllint disable-line rule:commas
    - {regexp: '^local2,local3\.\*',            line: 'local2,local3.*         -/var/log/localmessages'}    # yamllint disable-line rule:commas
    - {regexp: '^local4,local5\.\*',            line: 'local4,local5.*         -/var/log/localmessages'}    # yamllint disable-line rule:commas
    - {regexp: '^local6,local7\.\*',            line: 'local6,local7.*         -/var/log/localmessages'}    # yamllint disable-line rule:commas
