- ansible.builtin.debug:
    msg:
      - 'rsyslog-forwarding-configure.yml'

# https://www.rsyslog.com/sending-messages-to-a-remote-syslog-server/

- ansible.builtin.blockinfile:
    path: '/etc/rsyslog.conf'
    state: 'present'
    block: |
      # this is the simplest forwarding action:
      *.* action(type="omfwd" target="{{ stig__remote_syslog.server }}" port="{{ stig__remote_syslog.port }}" protocol="{{ stig__remote_syslog.proto }}")
    insertafter: 'EOF'
  register: 'result'
  failed_when:
    - 'result is failed'
    - 'result.rc != 257'
