- ansible.builtin.debug:
    msg:
      - 'sctp-off.yml'

- block:
    # First run "modprobe" to let the task fail when the kernel module is used.
    # This prevents the kernel module from being permanently disabled by "template".
  - community.general.modprobe:
      name: 'sctp'
      state: 'absent'
  - ansible.builtin.template:
      src: 'etc/modprobe.d/sctp.conf.j2'
      dest: '/etc/modprobe.d/sctp.conf'
