- ansible.builtin.debug:
    msg:
      - 'shell-timeout-configure.yml'

- ansible.builtin.blockinfile:
    path: '{{ item.path }}'
    state: '{{ item.state }}'
    marker: '# {mark} SHELL SETTINGS (ANSIBLE MANAGED)'
    block: |
      # Set session timeout per security requirements
      TMOUT={{ stig__shell_timeout }} ; export TMOUT
    create: true
    mode: 0o644
  loop:
    - path: '/etc/bashrc'
      state: 'present'
    - path: '/etc/profile'
      state: 'present'
