- ansible.builtin.debug:
    msg:
      - 'slapd-disable.yml'

- ansible.builtin.systemd:
    name: 'slapd'
    state: 'stopped'
    enabled: false
  when:
    - '"slapd.service" in ansible_facts["services"]'
    - 'ansible_facts["services"]["slapd.service"]["state"] == "running" or ansible_facts["services"]["slapd.service"]["status"] == "enabled"'
