- ansible.builtin.debug:
    msg:
      - 'smb-disable.yml'

- ansible.builtin.systemd:
    name: 'smb'
    state: 'stopped'
    enabled: false
  when:
    - '"smb.service" in ansible_facts["services"]'
    - 'ansible_facts["services"]["smb.service"]["state"] == "running" or ansible_facts["services"]["smb.service"]["status"] == "enabled"'
