- ansible.builtin.debug:
    msg:
      - 'snmpd-disable.yml'

- ansible.builtin.systemd:
    name: 'snmpd'
    state: 'stopped'
    enabled: false
  when:
    - '"snmpd.service" in ansible_facts["services"]'
    - 'ansible_facts["services"]["snmpd.service"]["state"] == "running" or ansible_facts["services"]["snmpd.service"]["status"] == "enabled"'
