- ansible.builtin.debug:
    msg:
      - 'sshd-x11forwarding-off.yml'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    create: false
    regexp: '(?i)^\s*X11Forwarding\s+'
    state: 'absent'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    create: true
    line: 'X11Forwarding no'
    state: 'present'
    insertbefore: '^[#\s]*Match'
    validate: '/usr/sbin/sshd -t -f %s'
