- ansible.builtin.debug:
    msg:
      - 'sshd-permitrootlogin-off.yml'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    create: false
    regexp: '(?i)^\s*PermitRootLogin\s+'
    state: 'absent'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    create: true
    line: 'PermitRootLogin no'
    state: 'present'
    insertbefore: '^[#\s]*Match'
    validate: '/usr/sbin/sshd -t -f %s'
