- ansible.builtin.debug:
    msg:
      - 'sshd-banner-configure.yml'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    create: false
    regexp: '(?i)^\s*Banner\s+'
    state: 'absent'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    create: true
    line: 'Banner /etc/issue.net'
    state: 'present'
    insertbefore: '^[#\s]*Match'
    validate: '/usr/sbin/sshd -t -f %s'
