- ansible.builtin.debug:
    msg:
      - 'sshd-maxstartups-configure.yml'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    create: false
    regexp: '(?i)^\s*MaxStartups\s+'
    state: 'absent'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    create: true
    line: 'MaxStartups 10:30:60'
    state: 'present'
    insertbefore: '^[#\s]*Match'
    validate: '/usr/sbin/sshd -t -f %s'
