- ansible.builtin.debug:
    msg:
      - 'sshd-macs-configure.yml'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    regexp: '^#?MACs'
    line: 'MACs {{ stig__sshd_macs }}'
    state: 'present'
    validate: '/usr/sbin/sshd -t -f %s'
  when:
    - 'stig__sshd_macs is defined'
    - 'stig__sshd_macs != ""'
