- ansible.builtin.debug:
    msg:
      - 'sshd-clientaliveinterval-configure.yml'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    create: false
    regexp: '(?i)^\s*ClientAliveInterval\s+'
    state: 'absent'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    create: true
    line: 'ClientAliveInterval {{ stig__sshd_clientaliveinterval }}'
    state: 'present'
    insertbefore: '^[#\s]*Match'
    validate: '/usr/sbin/sshd -t -f %s'
