- ansible.builtin.debug:
    msg:
      - 'sshd-allowtcpforwarding-off.yml'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    create: false
    regexp: '(?i)^\s*AllowTcpForwarding\s+'
    state: 'absent'

- ansible.builtin.lineinfile:
    path: '/etc/ssh/sshd_config'
    create: true
    line: 'AllowTcpForwarding no'
    state: 'present'
    insertbefore: '^[#\s]*Match'
    validate: '/usr/sbin/sshd -t -f %s'
