- ansible.builtin.debug:
    msg:
      - 'su-restrictions-configure.yml'

- ansible.builtin.lineinfile:
    path: '/etc/pam.d/su'
    create: false
    regexp: '(?i)^\s*auth\s+required\s+pam_wheel\.so\s+'
    state: 'absent'

- ansible.builtin.lineinfile:
    path: '/etc/pam.d/su'
    create: true
    line: 'auth           required        pam_wheel.so use_uid'
    state: 'present'

- ansible.builtin.user:
    name: 'root'
    groups: 'wheel'
