- ansible.builtin.debug:
    msg:
      - 'sysctl-net_ipv6_route_flush-on.yml'

- ansible.posix.sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: true
    state: 'present'
    reload: true
    ignoreerrors: true
  loop:
    - {name: 'net.ipv6.route.flush', value: 1}
  when:
    - 'ipv6_enabled'
