- ansible.builtin.debug:
    msg:
      - 'vfat-off.yml'

- block:
    # First run "modprobe" to let the task fail when the kernel module is used.
    # This prevents the kernel module from being permanently disabled by "template".
  - community.general.modprobe:
      name: 'vfat'
      state: 'absent'
  - ansible.builtin.template:
      src: 'etc/modprobe.d/vfat.conf.j2'
      dest: '/etc/modprobe.d/vfat.conf'
  when:
    - 'booted_in_bios_mode | bool'
