- ansible.builtin.debug:
    msg:
      - 'vsftpd-disable.yml'

- ansible.builtin.systemd:
    name: 'vsftpd'
    state: 'stopped'
    enabled: false
  when:
    - '"vsftpd.service" in ansible_facts["services"]'
    - 'ansible_facts["services"]["vsftpd.service"]["state"] == "running" or ansible_facts["services"]["vsftpd.service"]["status"] == "enabled"'
