- ansible.builtin.debug:
    msg:
      - 'wifi-off.yml'

- ansible.builtin.command: 'rpm -q NetworkManager'
  args:
    warn: false
  check_mode: false
  changed_when: false
  become: true
  register: 'nmcli_available'
  failed_when: false

- ansible.builtin.command: 'nmcli radio all off'
  become: true
  changed_when: false
  when:
    - 'nmcli_available.rc == 0'
